(define (pascal i j)
  (if (or (= j 1) (= j i)) 
        1
        (+ (pascal (- i 1) (- j 1))
                 (pascal (- i 1) j)
        )
  )
)
(define (pascal-display n)
  (define (pascal-iter r c)
    (display (pascal r c)) (display " ")
    (cond ((and (= r n) (= c n)) (newline)) 
          ((= c r) (newline) (pascal-iter (+ r 1) 1))
          (else (pascal-iter r (+ c 1)))
          )
    )
  (pascal-iter 1 1)
  )
(pascal-display 10)
